### ISSUE TITLE
Binding '<Ctrl><Alt>space' failed!

### ISSUE THREAD

**Issue by ppavacic** [hardpixel/gnome-hud#11]
I'm currently running Gnome 3.32 on Fedora 30 on Wayland and when I try running gnomehud I get an error:
** (-c:4381): WARNING **: 00:35:03.461: Binding '<Ctrl><Alt>space' failed!
Any ideas what might be wrong? Ctrl + alt + space combo isn't bound to anything.

**Comment by ppavacic** [comment]
It works in Xorg. I mean it can bind that key combination. Menus are empty tho, I've installed all required packages.

**Comment by lastweakness** [comment]
Same issue, did you ever find any fix?

**Comment by ppavacic** [comment]
Switch to Xorg. I believe with Wayland it is not possible because of the design of compositor.

**Comment by jonian** [comment]
Closing, as this can't be fixed for wayland. Use the readme instructions [here](https://github.com/hardpixel/gnome-hud#usage) to set custom shortcut.
