### ISSUE TITLE
Option to not swallow menu/how to configure key binding?

### ISSUE THREAD

**Issue by jc-huetter** [hardpixel/gnome-hud#12]
Hi,

I just found out about this very cool application! I have two questions/issues though:

1. Is there an option to keep showing the menu while gnome-hud is running? Right now, when I start it, the regular menus dissapear.
2. Is there a way to configure the standard key binding of `<Ctrl><Alt>Space`?

Thanks!

**Comment by jonian** [comment]
Hi @jc-huetter,

> Is there an option to keep showing the menu while gnome-hud is running?

There is an option for [appmenu-gtk-module](https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/subprojects/appmenu-gtk-module/README.md), you can change it using `dconf-editor`. The option key is `org.appmenu.gtk-module.always-show-inner-menu`.

For Qt apps, I don't know, you have to check the docs for qt4 and qt5 appmenu packages.

> Is there a way to configure the standard key binding of <Ctrl><Alt>Space?

When running from the terminal, no, there is no option. Check the [readme](https://github.com/hardpixel/gnome-hud#usage) on how to use custom keybindings with other applications, like [gnome settings](https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en).

**Comment by jc-huetter** [comment]
Great, thanks! I guess I was fuzzy on the second part, so for the sake of other people searching for it: First, start `gnomehud-service`. Then, bind `gnomehud` or `gnomehud-rofi` to a custom key in the GNOME settings.
