### ISSUE TITLE
Does not work with Visual Studio Code

### ISSUE THREAD

**Issue by andoniu** [hardpixel/gnome-hud#2]
Only the Quit menu is displayed. Would bu nice to see the errors (if any) if I run it from command line
I am using it with Fedora 28/ i3wm

**Comment by andoniu** [comment]
I tried several hud apps, this is the best available so far, the code is clean, congrats!

**Comment by jonian** [comment]
Hi, currently this does not work with electron apps, firefox, chrome and probably more applications.
When only the "Quit" menu item is displayed, it means the app menu was not found in dbus.
