### ISSUE TITLE
expose actions not in the menubar

### ISSUE THREAD

**Issue by ghost** [hardpixel/gnome-hud#5]
https://github.com/p-e-w/plotinus

A lot of gnome 3 applications are beginning to move options out of the main menu-bar. The plotinus program is able to collect all actions exposed via dbus. Seems like it would be a good idea to concatenate ALL actions, not just those in the menu.

**Comment by gmlshadi** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1132

Gnome is intent on killing menu-bars: Actions are going to be strewn across various hamburger menus and buttons. But they also removing support for modules with GTK+4 meaning that the current global menu will cease to work with newer apps. 

So it seems that the only way to keep this functionality moving forward is to just create your own menus from the exposed d-bus commands (maybe even allowing users to add custom ones)

**Comment by jonian** [comment]
Has been implemented as seen [here](https://github.com/hardpixel/gnome-hud/blob/master/gnomehud/utils/menu.py#L192).
